import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <header className="bg-white shadow-md">
        <nav className="container mx-auto px-4 py-4 flex items-center justify-between">
          <div className="text-xl font-bold text-gray-800">MyApp</div>
          <div className="space-x-6">
            <Link href="/" className="text-gray-600 hover:text-blue-600 transition-colors duration-200">
              Home
            </Link>
            <Link href="/blog" className="text-gray-600 hover:text-blue-600 transition-colors duration-200">
              Blog
            </Link>
            <Link href="/contact" className="text-gray-600 hover:text-blue-600 transition-colors duration-200">
              Contact
            </Link>
            <Link href="/products" className="text-gray-600 hover:text-blue-600 transition-colors duration-200">
              Product
            </Link>
            <Link href="/login" className="text-white bg-blue-600 hover:bg-blue-700 px-4 py-2 rounded transition duration-200">
              Login
            </Link>
          </div>
        </nav>
      </header>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
